#-------------------------------
# General Site Settings
title: nooooob coder
logo: logo.svg # You can add own logo.
description: blog for sharing code and restaurant 


#-------------------------------
# Author Settings
author:
  name: nooooob coder
  image: 01.jpg
  say-hello: Hello, I’m <strong>Nooooob coder</strong>
  bio: talks, and writes about <strong>nodejs</strong>, <strong>golang</strong>, <strong>C++</strong>, and dev. I am fan of korean singer "Younha". Loves <a href="#">music</a> & car wash.


#-------------------------------
# Contact links
twitter: null #https://twitter.com/ # Add your Twitter handle
facebook: null #https://facebook.com/ # Add your Facebook handle
dribbble: null #https://dribbble.com/ # Add your Dribbble handle
instagram: https://www.instagram.com/waddofficial/ # Add your Instagram handle
pinterest: null #https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: waddofficial # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e